/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:275781:
  appc.background(230);
} //_CODE_:window1:275781:

public void addbutton(GButton source, GEvent event) { //_CODE_:add:708290:
  createEvent();
  
} //_CODE_:add:708290:

public void clearbutton(GButton source, GEvent event) { //_CODE_:clear:884790:
  events.clear();
} //_CODE_:clear:884790:

public void startlist(GDropList source, GEvent event) { //_CODE_:start:737259:
  if (event == GEvent.SELECTED) {
   String selectedStart =  source.getSelectedText();
   
   for (City a: cityList) {
     if (a.name.equals(selectedStart)) {
        startCity = a;
     }
     }
     
     println("Start City is", startCity.name);
   }
  
  } //_CODE_:start:737259:

public void endlist(GDropList source, GEvent event) { //_CODE_:end:696236:
    if (event == GEvent.SELECTED) {
   String selectedEnd =  source.getSelectedText();
   
   for (City a: cityList) {
     if (a.name.equals(selectedEnd)) {
        endCity = a;
     }
     }
     
     println("Start City is", endCity.name);
   }
  
  } //_CODE_:end:696236:

public void categorylist(GDropList source, GEvent event) { //_CODE_:category:612875:
  println("category - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:category:612875:

public void budgetslider(GCustomSlider source, GEvent event) { //_CODE_:budget:394047:
  println("budget - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:budget:394047:

public void starsslider(GCustomSlider source, GEvent event) { //_CODE_:stars:653742:
  println("stars - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:stars:653742:

public void durationslider(GSlider source, GEvent event) { //_CODE_:duration:258808:
  //createEvent();
  //clear();
} //_CODE_:duration:258808:

public void starttimelist(GDropList source, GEvent event) { //_CODE_:startTimes:262427:
} //_CODE_:startTimes:262427:

public void mapmakerbutton(GButton source, GEvent event) { //_CODE_:mapmaker:647962:
 ArrayList<Location> test = new ArrayList<Location>();
 // Create locations with correct constructor
  if (startCity != null && endCity != null) {
    
    test.add(startCity);
    test.add(endCity);
    
    roadPoints = retrievePoints(test);
    
    if (roadPoints != null && roadPoints.size() > 0) {
    drawRoad = true;
    println("Road loaded with " + roadPoints.size() + " points");
  } else {
    println("Failed to load road");
  }
  
    
  }
  
  
  
  
 } //_CODE_:mapmaker:647962:

public void calendarbutton(GButton source, GEvent event) { //_CODE_:calendar:693927:
  if (showCalendar) showCalendar = false;
  else showCalendar = true;
} //_CODE_:calendar:693927:

public void redslider(GSlider source, GEvent event) { //_CODE_:rvalue:820318:
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:rvalue:820318:

public void greenslider(GSlider source, GEvent event) { //_CODE_:gvalue:483320:
  println("slider2 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:gvalue:483320:

public void blueslider(GSlider source, GEvent event) { //_CODE_:bvalue:247986:
  println("slider3 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:bvalue:247986:

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:411559:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton1:411559:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "window1", 0, 0, 380, 480, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(window1, 15, 16, 129, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Choose a starting city:");
  label1.setOpaque(false);
  label2 = new GLabel(window1, 15, 79, 139, 17);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Choose an ending city:");
  label2.setOpaque(false);
  label4 = new GLabel(window1, 21, 251, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Category:");
  label4.setOpaque(false);
  label6 = new GLabel(window1, 17, 403, 80, 20);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Star Rating:");
  label6.setOpaque(false);
  label7 = new GLabel(window1, 215, 103, 80, 20);
  label7.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label7.setText("Calendar");
  label7.setOpaque(true);
  label8 = new GLabel(window1, 214, 121, 80, 20);
  label8.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label8.setText("Start time:");
  label8.setOpaque(false);
  label9 = new GLabel(window1, 209, 169, 92, 36);
  label9.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label9.setText("Duration (Minutes)");
  label9.setOpaque(false);
  add = new GButton(window1, 167, 370, 80, 30);
  add.setText("Add");
  add.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  add.addEventHandler(this, "addbutton");
  clear = new GButton(window1, 259, 370, 80, 30);
  clear.setText("Clear");
  clear.setLocalColorScheme(GCScheme.RED_SCHEME);
  clear.addEventHandler(this, "clearbutton");
  start = new GDropList(window1, 38, 45, 90, 80, 3, 10);
  start.setItems(loadStrings("list_737259"), 0);
  start.addEventHandler(this, "startlist");
  end = new GDropList(window1, 38, 106, 90, 80, 3, 10);
  end.setItems(loadStrings("list_696236"), 0);
  end.addEventHandler(this, "endlist");
  category = new GDropList(window1, 20, 277, 90, 80, 3, 10);
  category.setItems(loadStrings("list_612875"), 0);
  category.addEventHandler(this, "categorylist");
  budget = new GCustomSlider(window1, 18, 331, 100, 53, "blue18px");
  budget.setLimits(1, 1, 3);
  budget.setShowTicks(true);
  budget.setNumberFormat(G4P.INTEGER, 0);
  budget.setOpaque(false);
  budget.addEventHandler(this, "budgetslider");
  stars = new GCustomSlider(window1, 16, 406, 100, 64, "red_yellow18px");
  stars.setShowValue(true);
  stars.setLimits(1.0, 0.0, 10.0);
  stars.setShowTicks(true);
  stars.setNumberFormat(G4P.DECIMAL, 1);
  stars.setOpaque(false);
  stars.addEventHandler(this, "starsslider");
  duration = new GSlider(window1, 205, 199, 100, 55, 10.0);
  duration.setShowValue(true);
  duration.setShowLimits(true);
  duration.setLimits(30, 10, 300);
  duration.setShowTicks(true);
  duration.setNumberFormat(G4P.INTEGER, 0);
  duration.setOpaque(false);
  duration.addEventHandler(this, "durationslider");
  label5 = new GLabel(window1, 19, 312, 80, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Budget:");
  label5.setOpaque(false);
  label10 = new GLabel(window1, 15, 333, 25, 20);
  label10.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label10.setText("$");
  label10.setOpaque(false);
  label11 = new GLabel(window1, 53, 333, 24, 20);
  label11.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label11.setText("$$");
  label11.setOpaque(false);
  label12 = new GLabel(window1, 90, 333, 32, 21);
  label12.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label12.setText("$$$");
  label12.setOpaque(false);
  startTimes = new GDropList(window1, 210, 142, 90, 80, 3, 10);
  startTimes.setItems(loadStrings("list_262427"), 0);
  startTimes.addEventHandler(this, "starttimelist");
  label13 = new GLabel(window1, 17, 212, 143, 20);
  label13.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label13.setText("Attractions + Stops:");
  label13.setOpaque(true);
  mapmaker = new GButton(window1, 39, 144, 80, 30);
  mapmaker.setText("Create Map!");
  mapmaker.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  mapmaker.addEventHandler(this, "mapmakerbutton");
  calendar = new GButton(window1, 211, 406, 80, 30);
  calendar.setText("View Calendar");
  calendar.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  calendar.addEventHandler(this, "calendarbutton");
  rvalue = new GSlider(window1, 205, 284, 100, 40, 10.0);
  rvalue.setLimits(123, 0, 255);
  rvalue.setNumberFormat(G4P.INTEGER, 0);
  rvalue.setLocalColorScheme(GCScheme.RED_SCHEME);
  rvalue.setOpaque(false);
  rvalue.addEventHandler(this, "redslider");
  gvalue = new GSlider(window1, 205, 311, 100, 40, 10.0);
  gvalue.setLimits(123, 0, 255);
  gvalue.setNumberFormat(G4P.INTEGER, 0);
  gvalue.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  gvalue.setOpaque(false);
  gvalue.addEventHandler(this, "greenslider");
  bvalue = new GSlider(window1, 205, 340, 100, 40, 10.0);
  bvalue.setLimits(123, 0, 255);
  bvalue.setNumberFormat(G4P.INTEGER, 0);
  bvalue.setOpaque(false);
  bvalue.addEventHandler(this, "blueslider");
  label3 = new GLabel(window1, 216, 270, 80, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Colour");
  label3.setOpaque(false);
  imgButton1 = new GImageButton(window1, 185, 5, 150, 93, new String[] { "journeylog.png", "journeylog.png", "journeylog.png" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GLabel label1; 
GLabel label2; 
GLabel label4; 
GLabel label6; 
GLabel label7; 
GLabel label8; 
GLabel label9; 
GButton add; 
GButton clear; 
GDropList start; 
GDropList end; 
GDropList category; 
GCustomSlider budget; 
GCustomSlider stars; 
GSlider duration; 
GLabel label5; 
GLabel label10; 
GLabel label11; 
GLabel label12; 
GDropList startTimes; 
GLabel label13; 
GButton mapmaker; 
GButton calendar; 
GSlider rvalue; 
GSlider gvalue; 
GSlider bvalue; 
GLabel label3; 
GImageButton imgButton1; 
