/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:275781:
  appc.background(230);
} //_CODE_:window1:275781:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:708290:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:708290:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:884790:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:884790:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:start:737259:
  println("start - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:start:737259:

public void dropList1_click2(GDropList source, GEvent event) { //_CODE_:end:696236:
  println("end - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:end:696236:

public void dropList1_click3(GDropList source, GEvent event) { //_CODE_:category:612875:
  println("category - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:category:612875:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:budget:394047:
  println("budget - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:budget:394047:

public void custom_slider1_change2(GCustomSlider source, GEvent event) { //_CODE_:stars:653742:
  println("stars - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:stars:653742:

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:duration:258808:
  println("duration - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:duration:258808:

public void dropList1_click4(GDropList source, GEvent event) { //_CODE_:startTimes:262427:
  println("startTimes - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:startTimes:262427:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "window1", 0, 0, 380, 480, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(window1, 15, 16, 129, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Choose a starting city:");
  label1.setOpaque(false);
  label2 = new GLabel(window1, 15, 79, 139, 17);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Choose an ending city:");
  label2.setOpaque(false);
  label4 = new GLabel(window1, 18, 193, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Category:");
  label4.setOpaque(false);
  label6 = new GLabel(window1, 15, 349, 80, 20);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Star Rating:");
  label6.setOpaque(false);
  label7 = new GLabel(window1, 220, 167, 80, 20);
  label7.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label7.setText("Calendar");
  label7.setOpaque(true);
  label8 = new GLabel(window1, 220, 194, 80, 20);
  label8.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label8.setText("Start time:");
  label8.setOpaque(false);
  label9 = new GLabel(window1, 212, 247, 92, 36);
  label9.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label9.setText("Duration (Minutes)");
  label9.setOpaque(false);
  button1 = new GButton(window1, 167, 339, 80, 30);
  button1.setText("Add");
  button1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(window1, 259, 339, 80, 30);
  button2.setText("Clear");
  button2.setLocalColorScheme(GCScheme.RED_SCHEME);
  button2.addEventHandler(this, "button2_click1");
  start = new GDropList(window1, 38, 45, 90, 80, 3, 10);
  start.setItems(loadStrings("list_737259"), 0);
  start.addEventHandler(this, "dropList1_click1");
  end = new GDropList(window1, 38, 106, 90, 80, 3, 10);
  end.setItems(loadStrings("list_696236"), 0);
  end.addEventHandler(this, "dropList1_click2");
  category = new GDropList(window1, 38, 223, 90, 80, 3, 10);
  category.setItems(loadStrings("list_612875"), 0);
  category.addEventHandler(this, "dropList1_click3");
  budget = new GCustomSlider(window1, 17, 281, 100, 53, "blue18px");
  budget.setLimits(1, 1, 3);
  budget.setShowTicks(true);
  budget.setNumberFormat(G4P.INTEGER, 0);
  budget.setOpaque(false);
  budget.addEventHandler(this, "custom_slider1_change1");
  stars = new GCustomSlider(window1, 16, 363, 100, 64, "red_yellow18px");
  stars.setShowValue(true);
  stars.setLimits(1, 0, 10);
  stars.setShowTicks(true);
  stars.setNumberFormat(G4P.INTEGER, 0);
  stars.setOpaque(false);
  stars.addEventHandler(this, "custom_slider1_change2");
  duration = new GSlider(window1, 208, 271, 100, 55, 10.0);
  duration.setShowValue(true);
  duration.setShowLimits(true);
  duration.setLimits(1, 0, 300);
  duration.setShowTicks(true);
  duration.setNumberFormat(G4P.INTEGER, 0);
  duration.setOpaque(false);
  duration.addEventHandler(this, "slider1_change1");
  label5 = new GLabel(window1, 17, 249, 80, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Budget:");
  label5.setOpaque(false);
  label10 = new GLabel(window1, 11, 286, 25, 20);
  label10.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label10.setText("$");
  label10.setOpaque(false);
  label11 = new GLabel(window1, 46, 285, 24, 20);
  label11.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label11.setText("$$");
  label11.setOpaque(false);
  label12 = new GLabel(window1, 83, 285, 32, 21);
  label12.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label12.setText("$$$");
  label12.setOpaque(false);
  startTimes = new GDropList(window1, 215, 221, 90, 80, 3, 10);
  startTimes.setItems(loadStrings("list_262427"), 0);
  startTimes.addEventHandler(this, "dropList1_click4");
  label13 = new GLabel(window1, 14, 167, 143, 20);
  label13.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label13.setText("Attractions + Stops:");
  label13.setOpaque(true);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GLabel label1; 
GLabel label2; 
GLabel label4; 
GLabel label6; 
GLabel label7; 
GLabel label8; 
GLabel label9; 
GButton button1; 
GButton button2; 
GDropList start; 
GDropList end; 
GDropList category; 
GCustomSlider budget; 
GCustomSlider stars; 
GSlider duration; 
GLabel label5; 
GLabel label10; 
GLabel label11; 
GLabel label12; 
GDropList startTimes; 
GLabel label13; 
