/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:275781:
  appc.background(230);
} //_CODE_:window1:275781:

public void startlist(GDropList source, GEvent event) { //_CODE_:start:737259:
  if (event == GEvent.SELECTED) {
    String selectedStart = source.getSelectedText();

    if (selectedStart.equals("Select a city")) {
      startCity = null; // no real city selected
      return;
    }

    for (City a: cityList) {
      if (a.name.equals(selectedStart)) {
        startCity = a;
        break;
      }
    }
  }
} //_CODE_:start:737259:

public void endlist(GDropList source, GEvent event) { //_CODE_:end:696236:
    if (event == GEvent.SELECTED) { 
   String selectedEnd =  source.getSelectedText();
   
   
     if (selectedEnd.equals("Select a city")) {
      endCity = null; //no city selected 
      return;
    }
    
    
   for (City a: cityList) {
     if (a.name.equals(selectedEnd)) {
        endCity = a;
     }
     }
     
   }
  } //_CODE_:end:696236:

public void categorylist(GDropList source, GEvent event) { //_CODE_:category:612875:

} //_CODE_:category:612875:

public void budgetslider(GCustomSlider source, GEvent event) { //_CODE_:budget:394047:

} //_CODE_:budget:394047:

public void starsslider(GCustomSlider source, GEvent event) { //_CODE_:stars:653742:
} //_CODE_:stars:653742:

public void mapmakerbutton(GButton source, GEvent event) { //_CODE_:mapmaker:647962:
 ArrayList<Location> currentRoute = new ArrayList<Location>(); // temp list to hold the current cities and attractions
 
 // Create locations with correct constructor
 if (startCity != null && endCity != null) {
    
    currentRoute.add(startCity); //add start city to the route list 
    
    // Add all attractions from events calendar in chronological order
    for (Event e : events) {
      // Find the attraction that matches this event's name
      for (attractions a : attractionList) {
        if (a.name.equals(e.name)) {
          currentRoute.add(a); //add attraction as a stop
          break;
        }
      }
    }
    
    currentRoute.add(endCity); //add end city to the end list 
    
    //retrieve the road points using the OSRM API (return list of interpolated points)
    roadPoints = retrievePoints(currentRoute);
    
    //check if the road return with valid points 
    if (roadPoints != null && roadPoints.size() > 0) {
      drawRoad = true; //enable smooth road drawing 
    } else {
      println("Failed to load road");
    }
  }
} //_CODE_:mapmaker:647962:

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:411559:
} //_CODE_:imgButton1:411559:

public void routeinfo(GButton source, GEvent event) { //_CODE_:info:298949:
  if (showInfo) showInfo = false;
  else showInfo = true;
} //_CODE_:info:298949:

public void imgButton2_click1(GImageButton source, GEvent event) { //_CODE_:imgButton2:508188:
  println("imgButton2 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton2:508188:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:eventswin:200472:
  appc.background(230);
} //_CODE_:eventswin:200472:

public void durationslider(GSlider source, GEvent event) { //_CODE_:duration:451846:
} //_CODE_:duration:451846:

public void redslider(GSlider source, GEvent event) { //_CODE_:rvalue:756733:
} //_CODE_:rvalue:756733:

public void greenslider(GSlider source, GEvent event) { //_CODE_:gvalue:736120:
} //_CODE_:gvalue:736120:

public void blueslider(GSlider source, GEvent event) { //_CODE_:bvalue:417253:
} //_CODE_:bvalue:417253:

public void addbutton(GButton source, GEvent event) { //_CODE_:add:692087:
  createEvent(selected);
  //eventswin.setVisible(false);
} //_CODE_:add:692087:

public void clearbutton(GButton source, GEvent event) { //_CODE_:clear:890039:
  events.clear(); //clear all events 
} //_CODE_:clear:890039:

public void calendarbutton(GButton source, GEvent event) { //_CODE_:calendar:436293:
  if (showCalendar) showCalendar = false;
  else showCalendar = true;
} //_CODE_:calendar:436293:

public void starttimelist(GDropList source, GEvent event) { //_CODE_:startTimes:448248:
} //_CODE_:startTimes:448248:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "window1", 0, 0, 380, 340, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(window1, 15, 16, 129, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Choose a starting city:");
  label1.setOpaque(false);
  label2 = new GLabel(window1, 15, 79, 139, 17);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Choose an ending city:");
  label2.setOpaque(false);
  label4 = new GLabel(window1, 184, 127, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Category:");
  label4.setOpaque(false);
  label6 = new GLabel(window1, 183, 174, 80, 20);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Star Rating:");
  label6.setOpaque(false);
  start = new GDropList(window1, 38, 45, 90, 220, 10, 10);
  start.setItems(loadStrings("list_737259"), 0);
  start.addEventHandler(this, "startlist");
  end = new GDropList(window1, 38, 106, 90, 80, 3, 10);
  end.setItems(loadStrings("list_696236"), 0);
  end.addEventHandler(this, "endlist");
  category = new GDropList(window1, 184, 152, 90, 80, 3, 10);
  category.setItems(loadStrings("list_612875"), 0);
  category.addEventHandler(this, "categorylist");
  budget = new GCustomSlider(window1, 183, 237, 100, 53, "green_red20px");
  budget.setLimits(1, 1, 3);
  budget.setShowTicks(true);
  budget.setNumberFormat(G4P.INTEGER, 0);
  budget.setOpaque(false);
  budget.addEventHandler(this, "budgetslider");
  stars = new GCustomSlider(window1, 183, 181, 100, 64, "red_yellow18px");
  stars.setShowValue(true);
  stars.setLimits(1.0, 0.0, 10.0);
  stars.setShowTicks(true);
  stars.setNumberFormat(G4P.DECIMAL, 1);
  stars.setOpaque(false);
  stars.addEventHandler(this, "starsslider");
  label5 = new GLabel(window1, 183, 226, 63, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Budget:");
  label5.setOpaque(false);
  label11 = new GLabel(window1, 217, 237, 28, 20);
  label11.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label11.setText("$$");
  label11.setOpaque(false);
  label12 = new GLabel(window1, 269, 237, 32, 21);
  label12.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label12.setText("$$$");
  label12.setOpaque(false);
  label13 = new GLabel(window1, 185, 103, 143, 20);
  label13.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label13.setText("Attractions + Stops:");
  label13.setOpaque(true);
  mapmaker = new GButton(window1, 43, 135, 80, 30);
  mapmaker.setText("Create Map!");
  mapmaker.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  mapmaker.addEventHandler(this, "mapmakerbutton");
  imgButton1 = new GImageButton(window1, 185, 5, 150, 93, new String[] { "journeylog.png", "journeylog.png", "journeylog.png" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  info = new GButton(window1, 46, 172, 72, 38);
  info.setText("Show route info");
  info.addEventHandler(this, "routeinfo");
  label3 = new GLabel(window1, 177, 237, 20, 24);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("$");
  label3.setOpaque(false);
  imgButton2 = new GImageButton(window1, 18, 216, 131, 116, new String[] { "background.png", "background.png", "background.png" } );
  imgButton2.addEventHandler(this, "imgButton2_click1");
  eventswin = GWindow.getWindow(this, "eventswin", 0, 0, 240, 250, JAVA2D);
  eventswin.noLoop();
  eventswin.setActionOnClose(G4P.KEEP_OPEN);
  eventswin.addDrawHandler(this, "win_draw1");
  duration = new GSlider(eventswin, 20, 116, 100, 52, 10.0);
  duration.setShowValue(true);
  duration.setLimits(30, 10, 300);
  duration.setShowTicks(true);
  duration.setNumberFormat(G4P.INTEGER, 0);
  duration.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  duration.setOpaque(false);
  duration.addEventHandler(this, "durationslider");
  rvalue = new GSlider(eventswin, 132, 110, 100, 40, 10.0);
  rvalue.setLimits(255, 0, 255);
  rvalue.setNumberFormat(G4P.INTEGER, 0);
  rvalue.setLocalColorScheme(GCScheme.RED_SCHEME);
  rvalue.setOpaque(false);
  rvalue.addEventHandler(this, "redslider");
  gvalue = new GSlider(eventswin, 131, 139, 100, 40, 10.0);
  gvalue.setLimits(245, 0, 255);
  gvalue.setNumberFormat(G4P.INTEGER, 0);
  gvalue.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  gvalue.setOpaque(false);
  gvalue.addEventHandler(this, "greenslider");
  bvalue = new GSlider(eventswin, 131, 162, 100, 40, 10.0);
  bvalue.setLimits(245, 0, 255);
  bvalue.setNumberFormat(G4P.INTEGER, 0);
  bvalue.setOpaque(false);
  bvalue.addEventHandler(this, "blueslider");
  add = new GButton(eventswin, 17, 169, 80, 30);
  add.setText("Add");
  add.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  add.addEventHandler(this, "addbutton");
  clear = new GButton(eventswin, 16, 204, 80, 30);
  clear.setText("Clear");
  clear.setLocalColorScheme(GCScheme.RED_SCHEME);
  clear.addEventHandler(this, "clearbutton");
  calendar = new GButton(eventswin, 142, 207, 80, 30);
  calendar.setText("View Calendar");
  calendar.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  calendar.addEventHandler(this, "calendarbutton");
  label14 = new GLabel(eventswin, 147, 86, 80, 20);
  label14.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label14.setText("Colour");
  label14.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  label14.setOpaque(false);
  label15 = new GLabel(eventswin, 81, 4, 80, 20);
  label15.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label15.setText("Calendar");
  label15.setOpaque(true);
  label16 = new GLabel(eventswin, 30, 94, 80, 24);
  label16.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label16.setText("Duration (Minutes)");
  label16.setOpaque(false);
  startTimes = new GDropList(eventswin, 78, 55, 90, 80, 3, 10);
  startTimes.setItems(loadStrings("list_448248"), 0);
  startTimes.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  startTimes.addEventHandler(this, "starttimelist");
  label17 = new GLabel(eventswin, 83, 33, 80, 20);
  label17.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label17.setText("Start Times:");
  label17.setOpaque(false);
  window1.loop();
  eventswin.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GLabel label1; 
GLabel label2; 
GLabel label4; 
GLabel label6; 
GDropList start; 
GDropList end; 
GDropList category; 
GCustomSlider budget; 
GCustomSlider stars; 
GLabel label5; 
GLabel label11; 
GLabel label12; 
GLabel label13; 
GButton mapmaker; 
GImageButton imgButton1; 
GButton info; 
GLabel label3; 
GImageButton imgButton2; 
GWindow eventswin;
GSlider duration; 
GSlider rvalue; 
GSlider gvalue; 
GSlider bvalue; 
GButton add; 
GButton clear; 
GButton calendar; 
GLabel label14; 
GLabel label15; 
GLabel label16; 
GDropList startTimes; 
GLabel label17; 
